--- config/elasticsearch.yml.orig	2018-09-26 13:30:23 UTC
+++ config/elasticsearch.yml
@@ -31,10 +31,12 @@
 # Path to directory where to store the data (separate multiple locations by comma):
 #
 #path.data: /path/to/data
+path.data: /var/db/elasticsearch
 #
 # Path to log files:
 #
 #path.logs: /path/to/logs
+path.logs: /var/log/elasticsearch
 #
 # ----------------------------------- Memory -----------------------------------
 #
